### PR TITLE
Fix innerHTML XSS vulnerability

### LINKED ISSUE #255: Uses innerHTML - potentially allows injection attacks
In renderList, the list items are rendered using innerHTML with no escaping.
If the mentions list is sourced from unsafe (user-sourced) data, this might allow an injection attack when a Quill user hits @.

https://github.com/quill-mention/quill-mention/blob/0aa9847719257496b14ac5401872c4e2ffcbc3d1/src/quill.mention.js#L391

A possible solution is to change renderItem to return a DOMelement, which uses textContent rather than innerHTML.

### PR DESCRIPTION
**Pull request by csculley**
Closes #255

This PR fixes the XSS vulnerability issues associated with using `innerHTML`.

Please let me know if anything needs to be changed. Thank you!

### CODE REVIEW

**Comment by thexeos** [comment]
This is a breaking change, so a major version bump and upgrade notes would be needed in readme.

**Comment by thexeos** [comment]
> Should we start a new `CHANGELOG.md` file in the root of the repository? Otherwise, I can add an upgrade notes section to the changelog if you'd like!

I like the README approach. It also means that people that visit **npm** page would see the important upgrade instructions.

**Review by thexeos — APPROVED** [review]
Looks good to me.

In summary:
- Existing Delta documents will loose their rendered HTML in `value`, but that is expected, as it may be currently polluted with XSS.
- New Delta documents will only ever store String (plain text) in `value` - the documentation reflects it.
- HTML rendering is still supported through the use of custom blots, that extend the default `MentionBlot`. They must implement a `render` method that returns an `Element`. Functionality of rendering HTML is maintained.
- Furthermore, the use of custom blot name means that `mention` objects with custom `data` payload will be explicitly handled by the custom blot, rather than the default one.
- I could not find any new XSS vectors (except for the end user introducing one in their `render` method).

Good work!

**Comment by MadSpindel** [comment]
Excellent job @csculley! I've now published version 4.0.0 to npm.

**Pull request merged**
