### PR TITLE
Backspace on Android, fixes #40

### LINKED ISSUE #40: delete fail on mobile
First 🙌 for an incredible plugin.

Deleting mentions doesn't work with the current release on mobile handsets I've tested (Nexus 5X + OnePlus6). I'm seeing distinct issues in Firefox and Chrome on Androids 8.1 and 9. gifs follow.

Is this a regression? As the recordings show, most of the functionality seems present (i.e. '@' triggering user menu, typing sub-selecting menu, being able to select a mention all seem to work ...)

on Chrome: (v69.0.3491.100 + v61.0.3163.98)
chrome v69 0 3497 100 on oneplus6 running oxygenos v9

on Firefox (v62.0.3)
firefox v62 0 3 on oneplus6 running oxygenos v9

Recordings done with OnePlus 6, running OxygenOS v9 (+ zoom.us for screensharing + gifox).
Behaviours reproduced on Nexus 5X running Android 8.1

### PR DESCRIPTION
**Pull request by keligijus**
Fixes #40. 

I've taken the code snippet from [this comment](https://github.com/quilljs/quill/issues/1985#issuecomment-387826451).

The Android keyboard still disappears, but it does not break the editor. It is possible to get the focus back to the editor and continue typing.

I've tested on Nexus 5X emulator in Android Studio.

### CODE REVIEW

**Comment by MadSpindel** [comment]
So this is a bug in Quill, not in Quill Mention, correct?

**Comment by keligijus** [comment]
Hey @MadSpindel. From my understanding, this is a bug with Android and how it deals with `contentEditable=false`.

I've seen people come up with all kinds of _hacks_ to mitigate the effects of this bug. The solution in this PR is just something that people have used with Quill.

Would you like some more background info, tests or any other improvements to the PR?

**Comment by MadSpindel** [comment]
Will close this since I don't think it's a bug in quill-mention.

**Comment by keligijus** [comment]
Hey @MadSpindel, sorry for an overdue reply.

Yes, this is a bug with Android. I am not sure if it affects Gbaord or all other keyboards for Android. I think it's not related to any specific keyboard, so all may be affected.

While this is not a bug with quill-mention, it does affect users that interact with quill-mention on their Android devices.

Currently, I'm using my fork of quill-mention and this seems to have fixed the issue for Android users.

**Comment by andrewrbe** [comment]
Really needed fixes. As I known it affects all Android keyboards. Current behavior  is really annoying on phones

**Comment by gamecraftCZ** [comment]
> 
> 
> Hey @MadSpindel, sorry for an overdue reply.
> 
> Yes, this is a bug with Android. I am not sure if it affects Gbaord or all other keyboards for Android. I think it's not related to any specific keyboard, so all may be affected.
> 
> While this is not a bug with quill-mention, it does affect users that interact with quill-mention on their Android devices.
> 
> Currently, I'm using my fork of quill-mention and this seems to have fixed the issue for Android users.

Can you please share what fork are you using?

**Comment by iltera** [comment]
I don't understand why this is not still implemented in quill-mention... It's still an issue people are facing and it clearly affects how quill-mention works, negatively.
Why not implementing the fix and save a lot of people some time?

**Pull request closed without merging**
