### PR TITLE
Added auto scroll on mention container when navigating to the list

### PR DESCRIPTION
**Pull request by abelski21**
Sets the scrollTop of the mention container based on the highlighted list item.

### CODE REVIEW

**Comment by MadSpindel** [comment]
Looks good to me. Thank you @abelski21!

**Comment by abelski21** [comment]
@MadSpindel we need to update the package on npm. Am I allowed to do that?

**Comment by MadSpindel** [comment]
@abelski21 I have published a new version (v0.2.6) on npm now.

**Comment by abelski21** [comment]
Thanks a lot @MadSpindel

**Pull request merged**
